mqtt:
  switch:
    - name: senseowifi_power
      unique_id: uniqueid__senseowifi_power
      icon: mdi:power
      #
      state_topic: "homie/senseo-wifi-rf21/machine/power"
      state_on: "true"
      state_off: "false"
      #
      command_topic: "homie/senseo-wifi-rf21/machine/power/set"
      payload_on: "true"
      payload_off: "false"
      #
      availability_topic: "homie/senseo-wifi-rf21/$state"
      payload_available: "ready"
      payload_not_available: "lost"

  binary_sensor:
    - name: senseowifi_out_of_water
      unique_id: uniqueid__senseowifi_out_of_water
      icon: mdi:water-off-outline
      #
      state_topic: "homie/senseo-wifi-rf21/machine/outOfWater"
      payload_on: "true"
      payload_off: "false"
      device_class: problem
      #
      availability_topic: "homie/senseo-wifi-rf21/$state"
      payload_available: "ready"
      payload_not_available: "lost"

    - name: senseowifi_cup_available
      unique_id: uniqueid__senseowifi_cup_available
      icon: mdi:coffee-outline
      #
      state_topic: "homie/senseo-wifi-rf21/machine/cupAvailable"
      payload_on: "true"
      payload_off: "false"
      #
      availability_topic: "homie/senseo-wifi-rf21/$state"
      payload_available: "ready"
      payload_not_available: "lost"

    - name: senseowifi_cup_full
      unique_id: uniqueid__senseowifi_cup_full
      icon: mdi:coffee
      #
      state_topic: "homie/senseo-wifi-rf21/machine/cupFull"
      payload_on: "true"
      payload_off: "false"
      #
      availability_topic: "homie/senseo-wifi-rf21/$state"
      payload_available: "ready"
      payload_not_available: "lost"

  sensor:
    - name: senseowifi_brewed_size
      unique_id: uniqueid__senseowifi_brewed_size
      icon: mdi:coffee-maker
      #
      state_topic: "homie/senseo-wifi-rf21/machine/brewedSize"
      #
      availability_topic: "homie/senseo-wifi-rf21/$state"
      payload_available: "ready"
      payload_not_available: "lost"

    - name: senseowifi_opstate
      unique_id: uniqueid__senseowifi_opstate
      icon: mdi:state-machine
      #
      state_topic: "homie/senseo-wifi-rf21/machine/opState"
      #
      availability_topic: "homie/senseo-wifi-rf21/$state"
      payload_available: "ready"
      payload_not_available: "lost"

    ##############################################################################

    - name: senseowifi_debug
      unique_id: uniqueid__senseowifi_debug
      icon: mdi:comment-text-multiple-outline
      #
      state_topic: "homie/senseo-wifi-rf21/machine/debug"
      #
      availability_topic: "homie/senseo-wifi-rf21/$state"
      payload_available: "ready"
      payload_not_available: "lost"
      #
      entity_category: diagnostic

    - name: senseowifi_rssi
      unique_id: uniqueid__senseowifi_rssi
      icon: mdi:signal-cellular-2
      #
      state_topic: "homie/senseo-wifi-rf21/$stats/signal"
      unit_of_measurement: "%"
      #
      availability_topic: "homie/senseo-wifi-rf21/$state"
      payload_available: "ready"
      payload_not_available: "lost"
      #
      device_class: signal_strength
      entity_category: diagnostic

    - name: senseowifi_uptime
      unique_id: uniqueid__senseowifi_uptime
      icon: mdi:av-timer
      #
      state_topic: "homie/senseo-wifi-rf21/$stats/uptime"
      unit_of_measurement: "s"
      #
      availability_topic: "homie/senseo-wifi-rf21/$state"
      payload_available: "ready"
      payload_not_available: "lost"

  ##############################################################################

  button:
    - name: senseowifi_brew_coffee_normal
      unique_id: uniqueid__senseowifi_brew_coffee_normal
      icon: mdi:coffee
      #
      command_topic: "homie/senseo-wifi-rf21/machine/brew/set"
      payload_press: "1cup"
      #
      availability_topic: "homie/senseo-wifi-rf21/$state"
      payload_available: "ready"
      payload_not_available: "lost"

    - name: senseowifi_brew_coffee_double
      unique_id: uniqueid__senseowifi_brew_coffee_double
      icon: mdi:coffee
      #
      command_topic: "homie/senseo-wifi-rf21/machine/brew/set"
      payload_press: "2cup"
      #
      availability_topic: "homie/senseo-wifi-rf21/$state"
      payload_available: "ready"
      payload_not_available: "lost"

  ##############################################################################

template:
  - sensor:
      - name: senseowifi_uptime_since
        unique_id: uniqueid__senseowifi_uptime_since
        state: >
          {% if is_state("sensor.senseowifi_uptime", "unavailable") %}
            "unavailable"
          {% else %}
            {{ ((as_timestamp(now() - timedelta(seconds=(states.sensor.senseowifi_uptime.state | int))) / 300) | round() * 300) | timestamp_local() }}
          {% endif %}
        icon: mdi:calendar-clock
        device_class: timestamp

##############################################################################

homeassistant:
  customize:
    switch.senseowifi_power:
      friendly_name: "SenseoWifi"
    binary_sensor.senseowifi_out_of_water:
      friendly_name: "SenseoWifi Wassertank leer Warnung"
    binary_sensor.senseowifi_cup_available:
      friendly_name: "SenseoWifi Tasse steht unter"
    binary_sensor.senseowifi_cup_full:
      friendly_name: "SenseoWifi Tasse voll"
    sensor.senseowifi_brewed_size:
      friendly_name: "SenseoWifi Zähler Kaffee-Brühungen (inkl. klein oder groß)"
    sensor.senseowifi_opstate:
      friendly_name: "SenseoWifi Operationszustand"
    sensor.senseowifi_debug:
      friendly_name: "SenseoWifi Debug-Nachrichten"
    sensor.senseowifi_uptime:
      friendly_name: "SenseoWifi Uptime"
    sensor.senseowifi_rssi:
      friendly_name: "SenseoWifi WLAN Signalstärke (RSSI)"
    button.senseowifi_brew_coffee_normal:
      friendly_name: "SenseoWifi Auslöser einfache Tasse brühen"
    button.senseowifi_brew_coffee_double:
      friendly_name: "SenseoWifi Auslöser große Tasse brühen"
    sensor.senseowifi_uptime_since:
      friendly_name: "SenseoWifi Letzter Neustart"

##############################################################################

input_boolean:
  senseowifi_brew_double_automated:
    name: "SenseoWifi Flag automatisch große Tasse brühen"
    initial: off
    icon: mdi:coffee

##############################################################################

automation:
  - id: "1636231455732"
    alias: Regel SenseoWifi ausschalten wenn zu lange im READY Zustand
    trigger:
      - platform: state
        entity_id: sensor.senseowifi_opstate
        to: "SENSEO_READY"
        for:
          minutes: 10
    action:
      - service: switch.turn_off
        entity_id: switch.senseowifi_power
      - service: mqtt.publish
        data:
          topic: "homie/senseo-wifi-rf21/machine/buzzer/set"
          payload: "tone4"

  ##############################################################################

  - id: "1611257542502"
    alias: Regel SenseoWifi Erinnerungston bei voller Tasse
    mode: single
    trigger:
      platform: state
      entity_id: binary_sensor.senseowifi_cup_full
      to: "on"
    action:
      - delay:
          minutes: 3
      - repeat:
          while:
            - condition: state
              entity_id: binary_sensor.senseowifi_cup_full
              state: "on"
            - condition: state # deal with a known firmware bug
              entity_id: binary_sensor.senseowifi_cup_available
              state: "on"
          sequence:
            - service: mqtt.publish
              data:
                topic: "homie/senseo-wifi-rf21/machine/buzzer/set"
                payload: "tone3"
            - delay:
                minutes: 1

  ##############################################################################

  - id: "1611257542601"
    alias: Regel SenseoWifi automatisch brühen (Schritt 1) Einschalten
    trigger:
      - platform: state
        entity_id: input_boolean.senseowifi_brew_double_automated
        to: "on"
    condition:
      - condition: state
        entity_id: switch.senseowifi_power
        state: "off"
    action:
      - service: mqtt.publish
        data:
          topic: "homie/senseo-wifi-rf21/machine/buzzer/set"
          payload: "tone4"
      - service: switch.turn_on
        entity_id: switch.senseowifi_power

  - id: "1611257542602"
    alias: Regel SenseoWifi automatisch brühen (Schritt 2) Brühen starten
    trigger:
      - platform: state
        entity_id: sensor.senseowifi_opstate
        to: "SENSEO_READY"
        for:
          seconds: 1 # let states settle
      - platform: state
        entity_id: input_boolean.senseowifi_brew_double_automated
        to: "on"
    condition:
      - condition: state
        entity_id: switch.senseowifi_power
        state: "on"
      - condition: state
        entity_id: sensor.senseowifi_opstate
        state: "SENSEO_READY"
      - condition: state
        entity_id: binary_sensor.senseowifi_out_of_water
        state: "off"
      - condition: state
        entity_id: binary_sensor.senseowifi_cup_available
        state: "on"
      - condition: state
        entity_id: binary_sensor.senseowifi_cup_full
        state: "off"
      - condition: state
        entity_id: input_boolean.senseowifi_brew_double_automated
        state: "on"
    action:
      - service: mqtt.publish
        data:
          topic: "homie/senseo-wifi-rf21/machine/brew/set"
          payload: "2cup"

  - id: "1611257542603"
    alias: Regel SenseoWifi automatisch brühen (Schritt 3) Ausschalten
    trigger:
      platform: state
      entity_id: sensor.senseowifi_opstate
      from: "SENSEO_BREWING"
      for:
        seconds: 1 # let states settle
    condition:
      - condition: state
        entity_id: input_boolean.senseowifi_brew_double_automated
        state: "on"
    action:
      - service: switch.turn_off
        entity_id: switch.senseowifi_power

  - id: "1611257542604"
    alias: Regel SenseoWifi automatisch brühen (Schritt 4) Flag löschen
    trigger:
      platform: state
      entity_id: switch.senseowifi_power
      to: "off"
    condition:
      - condition: state
        entity_id: input_boolean.senseowifi_brew_double_automated
        state: "on"
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.senseowifi_brew_double_automated

  - id: "1611257542605"
    alias: Regel SenseoWifi automatisch brühen (Schritt 5) Buzzerbestätigung
    trigger:
      platform: state
      entity_id: input_boolean.senseowifi_brew_double_automated
      to: "off"
    action:
      - service: mqtt.publish
        data:
          topic: "homie/senseo-wifi-rf21/machine/buzzer/set"
          payload: "tone4"

  ##############################################################################
